# ===============================
# DB PROFILE SWITCH
# ===============================
# Change this to:
#   local  = use localhost MySQL
#   cloud  = use Azure MySQL
db.profile=cloud


# ===============================
# LOCAL MYSQL (your Windows MySQL)
# ===============================
local.db.host=localhost
local.db.port=3306
local.db.name=payroll_db
local.db.user=root
local.db.pass=liolily010506

# local options
local.db.useSSL=false
local.db.sslMode=DISABLED
local.db.serverTimezone=Asia/Manila
local.db.allowPublicKeyRetrieval=true
local.db.useUnicode=true
local.db.characterEncoding=utf8


# ===============================
# CLOUD MYSQL (Azure)
# ===============================
# Use your Azure "Endpoint" exactly (from Azure portal Overview)
# Example: ebet-payroll-db.mysql.database.azure.com
cloud.db.host=ebet-payroll-db.mysql.database.azure.com
cloud.db.port=3306

# this should be the database name you created in Azure (you showed payroll_db)
cloud.db.name=payroll_db

# In your successful Workbench test, it shows User: exploringbearcat
cloud.db.user=exploringbearcat

# Put the admin password you set/reset in Azure here:
cloud.db.pass=Magic251012!

# Azure best practice: SSL ON
cloud.db.useSSL=true
cloud.db.sslMode=REQUIRED
cloud.db.serverTimezone=Asia/Manila
cloud.db.allowPublicKeyRetrieval=false
cloud.db.useUnicode=true
cloud.db.characterEncoding=utf8


# ===============================
# EMAIL SETTINGS (GMAIL)
# ===============================
owner.email=etime.exploringbearcat@gmail.com

smtp.user=etime.exploringbearcat@gmail.com
smtp.appPassword=sttu jkrb onmp hsdq

smtp.host=smtp.gmail.com
smtp.port=587
